version: '3.7'
services:
  postgres:
    image: postgres:16
    container_name: chinook_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: chinook_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: